shared:
    image: node:6

jobs:
    main:
        steps:
            - install: npm install
            - test: npm test
            - write-file: echo "hello" > $SD_ARTIFACTS_DIR/test
            - sleep: sleep 5000
