shared:
    image: node:6

jobs:
    main:
        steps:
            - install: npm install
            - test: npm test
            - write-file: echo "hello" > $SD_ARTIFACTS_DIR/test
            - curl: curl -X PUT -d 'hello' http://store.screwdriver.cd/v1/builds/1058/hello
